// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByZVVD456ngYHz9BJBuIjC3XpoLbArbDs',
    appId: '1:394333119239:web:7e3c48e0e209e1358fdba2',
    messagingSenderId: '394333119239',
    projectId: 'ideaapp-b0230',
    authDomain: 'ideaapp-b0230.firebaseapp.com',
    storageBucket: 'ideaapp-b0230.appspot.com',
    measurementId: 'G-37CD16M7E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWpYNblkOy2kU1LYQQiCjc26WnGS6ReY4',
    appId: '1:394333119239:android:314a4d378d737bdc8fdba2',
    messagingSenderId: '394333119239',
    projectId: 'ideaapp-b0230',
    storageBucket: 'ideaapp-b0230.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfhVP138AjN3EwBRmKEPmcChv-Dw5EWOk',
    appId: '1:394333119239:ios:37e9dd245be6ae2a8fdba2',
    messagingSenderId: '394333119239',
    projectId: 'ideaapp-b0230',
    storageBucket: 'ideaapp-b0230.appspot.com',
    iosClientId: '394333119239-tf7t073fn4844ubg3dqqjovdkn8ef25f.apps.googleusercontent.com',
    iosBundleId: 'com.smartchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfhVP138AjN3EwBRmKEPmcChv-Dw5EWOk',
    appId: '1:394333119239:ios:025b80a3cdcfd6158fdba2',
    messagingSenderId: '394333119239',
    projectId: 'ideaapp-b0230',
    storageBucket: 'ideaapp-b0230.appspot.com',
    iosClientId: '394333119239-5vd9l2hr3ie6da2r191sd05rbjrrsdme.apps.googleusercontent.com',
    iosBundleId: 'com.idea.ideaTest.RunnerTests',
  );
}
